### ISSUE TITLE
caps: wishlists and filling gaps

### ISSUE THREAD

**Issue by lucab** [oracle/railcar#1]
Hi, caps-rs author here. I was happily looking at your usecase, trying to identify existing gaps and bits that can be incorporated directly in the lib.

So far I think I have seen:
 * adding a serde-derive for Serialize/Deserialize directly on `caps::Capability`
 * adding some kind of `all()` returning a full hashset

Both seems reasonably feasible and easy to add. Any other feedback on it?

**Comment by lucab** [comment]
While at it, I think so far you are the first and only consumer of that crate. To increase its bus factor and keep it sane, would you be interested in comaintaining it (maintenance is very low anyway)?

I have an umbrella-org at https://github.com/camallo which already hosts several container-related crates, and caps-rs can also be moved there.

**Comment by vishvananda** [comment]
Hi lucab. The caps crate has been very useful. I was trying to minimize external dependencies in the oci library so I didn't need to serialize caps directly. If it were serializable I could potentially use it directly in oci, but it hasn't been a huge problem. An all() would definitely be valuable. I can't speak for oracle as a whole, but I'm happy to help with caps-rs on my personal time (although I don't have a lot of it since I have a new baby).

**Comment by vishvananda** [comment]
the newest version of the oci spec actually forces me to process all of the different types of caps individually, so an all isn't really needed any more. I think we can go ahead and close this.

**Comment by lucab** [comment]
Ack. I'm still planning to add `all()` at some point though. Also, you may be interested in reading https://github.com/opencontainers/runtime-spec/pull/675#issuecomment-279473070 about those new  sets.
